[package]
name = "esocietyhere/profileservice"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
MockDataStoreService = "buildthomas/mockdatastoreservice@1.0.3"